### ISSUE TITLE
依存不足

### ISSUE THREAD

**Issue by KenyuKurimoto** [sbgisen/brass_gazebo_battery#3]
`rosdep install`しても以下の依存不足により、ビルドが失敗する。

`libignition-math2-dev`

**Comment by jsupratman13** [comment]
rosdepは以下のリストを使用しています
https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml

こちらのリストに無ければrosdepが読み込めないので手動で`apt`から入れる必要があります

**Comment by h-wata** [comment]
@jsupratman13 さん、
~~頂いたリストを見ると、`libignition-math6-dev`があるのですがこちらでは依存解決しないんですかね？~~
#4 に書いてありましたね。失礼しました。
